name: todo
description: To-Do list

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: '^0.0.3'
  firebase_storage: '^0.0.7'
  image_picker: '^0.1.3'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/notebook.jpg

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
